apiVersion: v1
kind: Service
metadata:
  name: go-k8s-svc
  labels:
    app: go-k8s
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: go-k8s