apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-dep
  labels:
    app: go-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-k8s
  template:
    metadata:
      labels:
        app: go-k8s
    spec:
      containers:
        - name: go-k8s
          image: johnwalz97/go-k8s:0.0.1
          ports:
            - containerPort: 8080
